<unk>
<s>
</s>
dbp_E
dbp_B
dot
rdf_typetype
dbr_D
dbp_C
par_close
DISTINCT
dbr_B
dbo_BSeat
cr_close
SELECT
dbr_C
br_open
dbp_D
var_uri
dbo_E
dbo_C
dbp_A
var_x
br_close
par_open
dbo_D
dbo_B
dbr_A
WHERE
COUNT
cr_open
dbo_A
dbr_E
