prefix dbo:	<http://dbpedia.org/ontology/>
prefix dbr:	<http://dbpedia.org/resource/>
prefix foaf:	<http://xmlns.com/foaf/0.1/>
prefix wikipedia-en:	<http://en.wikipedia.org/wiki/>
prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix yago:	<http://dbpedia.org/class/yago/>
prefix wikidata:	<http://www.wikidata.org/entity/>
prefix owl:	<http://www.w3.org/2002/07/owl#>
prefix prov:	<http://www.w3.org/ns/prov#>
prefix virtrdf:	<http://www.openlinksw.com/schemas/virtrdf#>
prefix gold:	<http://purl.org/linguistics/gold/> 
prefix dbt:	<http://dbpedia.org/resource/Template:>
prefix dbp:	<http://dbpedia.org/property/>
prefix yago-res:	<http://yago-knowledge.org/resource/>
prefix georss:	<http://www.georss.org/georss/>
prefix ns14:	<http://ceb.dbpedia.org/resource/>
prefix ns22:	<http://www.britishpathe.com/video/>
prefix ns15:	<https://global.dbpedia.org/id/>
prefix geo:	<http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix xsd:	<http://www.w3.org/2001/XMLSchema#>
prefix dct:	<http://purl.org/dc/terms/> 
prefix dbc:	<http://dbpedia.org/resource/Category> 