select * where { { <https://dbpedia.org/resource/Ushiku_Daibutsu> ?a ?b . <https://dbpedia.org/resource/Japan> ?a ?b}UNION{ { <https://dbpedia.org/resource/Ushiku_Daibutsu> ?a ?b . <https://dbpedia.org/resource/Japan> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Ushiku_Daibutsu> . ?c ?d <https://dbpedia.org/resource/Japan>}} UNION{?c ?d <https://dbpedia.org/resource/Ushiku_Daibutsu> . ?c ?d <https://dbpedia.org/resource/Japan>}}
