select * where { { <https://dbpedia.org/resource/Victoria_Memorial_(Montreal) ?a ?b . <https://dbpedia.org/resource/Montreal> ?a ?b}UNION{ { <https://dbpedia.org/resource/Victoria_Memorial_(Montreal>) ?a ?b . <https://dbpedia.org/resource/Montreal> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Victoria_Memorial_(Montreal>) . ?c ?d <https://dbpedia.org/resource/Montreal>}} UNION{?c ?d <https://dbpedia.org/resource/Victoria_Memorial_(Montreal) . ?c ?d <https://dbpedia.org/resource/Montreal>}}
