select * where { { <https://dbpedia.org/resource/Denmark_Vesey_Monument> ?a ?b . <https://dbpedia.org/resource/Denmark_Vesey_Monument> ?a ?b}UNION{ { <https://dbpedia.org/resource/Denmark_Vesey_Monument> ?a ?b . <https://dbpedia.org/resource/Denmark_Vesey_Monument> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Denmark_Vesey_Monument> . ?c ?d <https://dbpedia.org/resource/Denmark_Vesey_Monument>}} UNION{?c ?d <https://dbpedia.org/resource/Denmark_Vesey_Monument> . ?c ?d <https://dbpedia.org/resource/Denmark_Vesey_Monument>}}
