select * where { { <https://dbpedia.org/resource/Diana_the_Huntress_Fountain> ?a ?b . <https://dbpedia.org/resource/Berlin> ?a ?b}UNION{ { <https://dbpedia.org/resource/Diana_the_Huntress_Fountain> ?a ?b . <https://dbpedia.org/resource/Berlin> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Diana_the_Huntress_Fountain> . ?c ?d <https://dbpedia.org/resource/Berlin>}} UNION{?c ?d <https://dbpedia.org/resource/Diana_the_Huntress_Fountain> . ?c ?d <https://dbpedia.org/resource/Berlin>}}
