select * where { { <https://dbpedia.org/resource/Deil's_Dyke> ?a ?b . <https://dbpedia.org/resource/Romania> ?a ?b}UNION{ { <https://dbpedia.org/resource/Deil's_Dyke> ?a ?b . <https://dbpedia.org/resource/Romania> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Deil's_Dyke> . ?c ?d <https://dbpedia.org/resource/Romania>}} UNION{?c ?d <https://dbpedia.org/resource/Deil's_Dyke> . ?c ?d <https://dbpedia.org/resource/Romania>}}
