select * where { { <https://dbpedia.org/resource/Washington_Monument_(Baltimore) ?a ?b . <https://dbpedia.org/resource/Washington_Monument_(Baltimore) ?a ?b}UNION{ { <https://dbpedia.org/resource/Washington_Monument_(Baltimore>) ?a ?b . <https://dbpedia.org/resource/Washington_Monument_(Baltimore>) ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Washington_Monument_(Baltimore>) . ?c ?d <https://dbpedia.org/resource/Washington_Monument_(Baltimore>)}} UNION{?c ?d <https://dbpedia.org/resource/Washington_Monument_(Baltimore) . ?c ?d <https://dbpedia.org/resource/Washington_Monument_(Baltimore)}}
