select * where { { <https://dbpedia.org/resource/Victory_Arch> ?a ?b . <https://dbpedia.org/resource/India> ?a ?b}UNION{ { <https://dbpedia.org/resource/Victory_Arch> ?a ?b . <https://dbpedia.org/resource/India> ?a ?b}UNION{?c ?d <https://dbpedia.org/resource/Victory_Arch> . ?c ?d <https://dbpedia.org/resource/India>}} UNION{?c ?d <https://dbpedia.org/resource/Victory_Arch> . ?c ?d <https://dbpedia.org/resource/India>}}
